#ifndef PRECOMPILED_H
#define PRECOMPILED_H

#ifndef _QX_TEST_EXPORT_H_
#define _QX_TEST_EXPORT_H_

#ifdef _BUILDING_TEST
#define TEST_DLL_EXPORT QX_DLL_EXPORT_HELPER
#else
#define TEST_DLL_EXPORT QX_DLL_IMPORT_HELPER
#endif

#ifdef _BUILDING_TEST
#define QX_REGISTER_HPP_QX_TEST QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_QX_TEST QX_REGISTER_CPP_EXPORT_DLL
#else // _BUILDING_QX_BLOG
#define QX_REGISTER_HPP_TEST QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_TEST QX_REGISTER_CPP_IMPORT_DLL
#endif // _BUILDING_QX_BLOG

#endif // _QX_BLOG_EXPORT_H_

#include <QxOrm.h>

#endif // PRECOMPILED_H
